"""add sql server and table permissions

Revision ID: 51eb2ff3b573
Revises: b32c14b88d27
Create Date: 2026-06-28 23:00:45.643298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51eb2ff3b573'
down_revision: Union[str, Sequence[str], None] = 'b32c14b88d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sql_server_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sql_server_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sql_server_id'], ['sql_servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sql_server_id', name='uq_user_sql_server_permission')
    )
    op.create_index(op.f('ix_user_sql_server_permissions_id'), 'user_sql_server_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sql_server_permissions_sql_server_id'), 'user_sql_server_permissions', ['sql_server_id'], unique=False)
    op.create_index(op.f('ix_user_sql_server_permissions_user_id'), 'user_sql_server_permissions', ['user_id'], unique=False)
    op.create_table('database_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=False),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('database_id', 'schema_name', 'table_name', name='uq_database_schema_table')
    )
    op.create_index(op.f('ix_database_tables_database_id'), 'database_tables', ['database_id'], unique=False)
    op.create_index(op.f('ix_database_tables_id'), 'database_tables', ['id'], unique=False)
    op.create_table('user_table_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['database_tables.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'table_id', name='uq_user_table_permission')
    )
    op.create_index(op.f('ix_user_table_permissions_id'), 'user_table_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_table_permissions_table_id'), 'user_table_permissions', ['table_id'], unique=False)
    op.create_index(op.f('ix_user_table_permissions_user_id'), 'user_table_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_table_permissions_user_id'), table_name='user_table_permissions')
    op.drop_index(op.f('ix_user_table_permissions_table_id'), table_name='user_table_permissions')
    op.drop_index(op.f('ix_user_table_permissions_id'), table_name='user_table_permissions')
    op.drop_table('user_table_permissions')
    op.drop_index(op.f('ix_database_tables_id'), table_name='database_tables')
    op.drop_index(op.f('ix_database_tables_database_id'), table_name='database_tables')
    op.drop_table('database_tables')
    op.drop_index(op.f('ix_user_sql_server_permissions_user_id'), table_name='user_sql_server_permissions')
    op.drop_index(op.f('ix_user_sql_server_permissions_sql_server_id'), table_name='user_sql_server_permissions')
    op.drop_index(op.f('ix_user_sql_server_permissions_id'), table_name='user_sql_server_permissions')
    op.drop_table('user_sql_server_permissions')
    # ### end Alembic commands ###
