"""expand audit logs for mcp execution

Revision ID: 5de0920daac6
Revises: d72229598903
Create Date: 2026-06-29 15:47:40.341661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5de0920daac6'
down_revision: Union[str, Sequence[str], None] = 'd72229598903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('sql_server_id', sa.Integer(), nullable=False))
    op.add_column('audit_logs', sa.Column('table_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('query_text', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('row_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_audit_logs_sql_server_id'), 'audit_logs', ['sql_server_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_id'), 'audit_logs', ['table_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'sql_servers', ['sql_server_id'], ['id'])
    op.create_foreign_key(None, 'audit_logs', 'database_tables', ['table_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_table_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_sql_server_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'row_count')
    op.drop_column('audit_logs', 'query_text')
    op.drop_column('audit_logs', 'table_id')
    op.drop_column('audit_logs', 'sql_server_id')
    # ### end Alembic commands ###
