"""extend audit logs

Revision ID: b32c14b88d27
Revises: 27438425869f
Create Date: 2026-06-28 02:50:31.292243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b32c14b88d27'
down_revision: Union[str, Sequence[str], None] = '27438425869f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('request_id', sa.String(length=100), nullable=False))
    op.add_column('audit_logs', sa.Column('tool_name', sa.String(length=150), nullable=False))
    op.add_column('audit_logs', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('audit_logs', 'details',
               existing_type=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000, collation='SQL_Latin1_General_CP1_CI_AS'),
               existing_nullable=True)
    op.drop_column('audit_logs', 'error_message')
    op.drop_column('audit_logs', 'duration_ms')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'tool_name')
    op.drop_column('audit_logs', 'request_id')
    # ### end Alembic commands ###
