"""create user_database_permissions table

Revision ID: bec8638c7f58
Revises: ecaa307e02d8
Create Date: 2026-06-28 02:42:21.028960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bec8638c7f58'
down_revision: Union[str, Sequence[str], None] = 'ecaa307e02d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_database_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['database_id'], ['databases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'database_id', name='uq_user_database_permission')
    )
    op.create_index(op.f('ix_user_database_permissions_database_id'), 'user_database_permissions', ['database_id'], unique=False)
    op.create_index(op.f('ix_user_database_permissions_id'), 'user_database_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_user_database_permissions_user_id'), 'user_database_permissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_database_permissions_user_id'), table_name='user_database_permissions')
    op.drop_index(op.f('ix_user_database_permissions_id'), table_name='user_database_permissions')
    op.drop_index(op.f('ix_user_database_permissions_database_id'), table_name='user_database_permissions')
    op.drop_table('user_database_permissions')
    # ### end Alembic commands ###
