"""create databases table

Revision ID: ecaa307e02d8
Revises: e8eab406ee65
Create Date: 2026-06-28 02:38:57.519204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecaa307e02d8'
down_revision: Union[str, Sequence[str], None] = 'e8eab406ee65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('databases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sql_server_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sql_server_id'], ['sql_servers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sql_server_id', 'name', name='uq_database_server_name')
    )
    op.create_index(op.f('ix_databases_id'), 'databases', ['id'], unique=False)
    op.create_index(op.f('ix_databases_sql_server_id'), 'databases', ['sql_server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_databases_sql_server_id'), table_name='databases')
    op.drop_index(op.f('ix_databases_id'), table_name='databases')
    op.drop_table('databases')
    # ### end Alembic commands ###
